(()=> {
const cfg=window.AUREN_SHOPIFY||{},$=id=>document.getElementById(id);
const demo=[
{id:"d1",title:"The Everyday Tote",category:"Carry",price:48,description:"A considered carryall for wherever the day takes you.",image:"https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=850&q=85",badge:"Bestseller"},
{id:"d2",title:"Form Ceramic Vessel",category:"Home",price:36,description:"A sculptural home for stems, branches, or nothing at all.",image:"https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=850&q=85",badge:"Small batch"},
{id:"d3",title:"Daily Ritual Oil",category:"Ritual",price:29,description:"A quiet moment of care, made part of your everyday.",image:"https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=850&q=85",badge:"New"},
{id:"d4",title:"The Slow Morning Cup",category:"Home",price:24,description:"Hand-feel ceramics for your first and favorite cup.",image:"https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?auto=format&fit=crop&w=850&q=85",badge:"Everyday essential"},
{id:"d5",title:"Weekend Carryall",category:"Carry",price:68,description:"Room for the essentials, and a little more breathing room.",image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=850&q=85",badge:"Made to move"},
{id:"d6",title:"Grounding Candle",category:"Ritual",price:32,description:"Soft light and a subtle scent for the end of the day.",image:"https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=850&q=85",badge:"Staff pick"}];
let products=demo.slice(),cart=[],category="All",term="",sort="featured",live=false,timer;
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(n)||0);
const esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(timer);timer=setTimeout(()=>$("toast").classList.remove("show"),2400)}
function renderProducts(){let list=products.filter(p=>(category==="All"||p.category===category)&&((p.title+" "+p.category+" "+p.description).toLowerCase().includes(term.toLowerCase())));if(sort==="low")list.sort((a,b)=>a.price-b.price);if(sort==="high")list.sort((a,b)=>b.price-a.price);$("products").innerHTML="";if(!list.length){$("products").innerHTML='<div class="no-results">No pieces found. Try another search or collection.</div>';return}list.forEach(p=>{const el=document.createElement("article");el.className="card";el.innerHTML='<div class="product-image"><img loading="lazy" src="'+esc(p.image)+'" alt="'+esc(p.title)+'"><span class="badge">'+esc(p.badge||p.category)+'</span><button class="quick-add" aria-label="Add '+esc(p.title)+' to bag" data-add="'+esc(p.id)+'">+</button></div><div class="product-info"><div><h3 class="product-title">'+esc(p.title)+'</h3><div class="product-category">'+esc(p.category)+' / AUREN EDIT</div></div><div class="price">'+money(p.price)+'</div><p class="product-desc">'+esc(p.description)+'</p></div>';$("products").appendChild(el)});document.querySelectorAll("[data-add]").forEach(b=>b.addEventListener("click",()=>add(b.dataset.add)))}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;if(live&&!p.variantId){toast("This product has no purchasable Shopify variant.");return}let item=cart.find(x=>x.id===id);if(item)item.quantity++;else cart.push({...p,quantity:1});renderCart();toast(p.title+" added to your bag.")}
function renderCart(){const count=cart.reduce((s,x)=>s+x.quantity,0),subtotal=cart.reduce((s,x)=>s+x.price*x.quantity,0);$("cartCount").textContent=count;$("drawerCount").textContent="("+count+")";$("subtotal").textContent=money(subtotal);$("cartItems").innerHTML="";cart.forEach(i=>{const row=document.createElement("div");row.className="cart-row";row.innerHTML='<img src="'+esc(i.image)+'" alt="'+esc(i.title)+'"><div><h4>'+esc(i.title)+'</h4><small>'+esc(i.category)+'</small><div class="qty"><button data-id="'+esc(i.id)+'" data-delta="-1">−</button><span>'+i.quantity+'</span><button data-id="'+esc(i.id)+'" data-delta="1">+</button></div></div><div class="row-price">'+money(i.price*i.quantity)+'</div>';$("cartItems").appendChild(row)});$("cartItems").querySelectorAll("[data-id]").forEach(b=>b.addEventListener("click",()=>{const i=cart.find(x=>x.id===b.dataset.id);i.quantity+=Number(b.dataset.delta);if(i.quantity<1)cart=cart.filter(x=>x.id!==i.id);renderCart()}));$("empty").style.display=count?"none":"flex";$("cartItems").style.display=count?"block":"none";$("checkout").style.display=count?"block":"none"}
function openCart(){$("drawer").classList.add("open");$("shade").classList.add("open");document.body.style.overflow="hidden"}function closeCart(){$("drawer").classList.remove("open");$("shade").classList.remove("open");document.body.style.overflow=""}
function setCategory(c){category=c;document.querySelectorAll("[data-category]").forEach(b=>b.classList.toggle("active",b.dataset.category===c));renderProducts();$("shop").scrollIntoView({behavior:"smooth"})}
document.querySelectorAll("[data-category]").forEach(b=>b.addEventListener("click",()=>setCategory(b.dataset.category)));
document.querySelectorAll("[data-jump]").forEach(a=>a.addEventListener("click",()=>setCategory(a.dataset.jump)));
$("sort").addEventListener("change",e=>{sort=e.target.value;renderProducts()});
$("cartOpen").addEventListener("click",openCart);$("cartClose").addEventListener("click",closeCart);$("shade").addEventListener("click",closeCart);$("continue").addEventListener("click",()=>{closeCart();$("shop").scrollIntoView({behavior:"smooth"})});
$("menuToggle").addEventListener("click",()=>$("nav").classList.toggle("open"));document.querySelectorAll("nav a").forEach(a=>a.addEventListener("click",()=>$("nav").classList.remove("open")));
$("searchToggle").addEventListener("click",()=>$("searchPanel").classList.toggle("open"));$("searchClose").addEventListener("click",()=>$("searchPanel").classList.remove("open"));$("search").addEventListener("input",e=>{term=e.target.value;renderProducts()});
$("newsletter").addEventListener("submit",e=>{e.preventDefault();$("newsletterMessage").textContent="Thanks for your interest. Connect a newsletter provider to collect subscriptions.";e.target.reset()});$("year").textContent=new Date().getFullYear();
async function api(query,variables){const res=await fetch("https://"+cfg.domain+"/api/"+(cfg.apiVersion||"2026-07")+"/graphql.json",{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Storefront-Access-Token":cfg.storefrontAccessToken},body:JSON.stringify({query,variables:variables||{}})});if(!res.ok)throw Error("Shopify returned "+res.status);const json=await res.json();if(json.errors&&json.errors.length)throw Error(json.errors[0].message);return json.data}
async function loadShopify(){if(!cfg.domain||!cfg.storefrontAccessToken)return;try{const d=await api("query AurenProducts { products(first: 24) { nodes { id title description productType featuredImage { url altText } priceRange { minVariantPrice { amount currencyCode } } variants(first: 10) { nodes { id title availableForSale price { amount currencyCode } } } } } }");const nodes=d.products.nodes||[];if(!nodes.length)return;products=nodes.map((p,i)=>{const v=(p.variants.nodes||[]).find(x=>x.availableForSale)||p.variants.nodes[0];const c=/carry|bag|travel|tote/i.test(p.title+" "+p.productType)?"Carry":/ritual|oil|candle|care|wellness/i.test(p.title+" "+p.productType)?"Ritual":"Home";return{id:p.id,title:p.title,category:c,price:Number(p.priceRange.minVariantPrice.amount),description:p.description||"Thoughtfully selected for everyday living.",image:p.featuredImage?p.featuredImage.url:demo[i%demo.length].image,badge:i===0?"From Shopify":"Considered essential",variantId:v&&v.id,currency:p.priceRange.minVariantPrice.currencyCode}});live=true;$("status").textContent="Live products from Shopify · Checkout integration active";renderProducts();toast("Shopify products connected.")}catch(e){console.error(e);$("status").textContent="Demo collection · Shopify connection needs checking";toast("Showing demo products; Shopify connection could not be verified.")}}
async function checkout(){if(!cart.length)return;if(!live){toast("Demo mode: connect your Shopify store to enable live checkout.");return}try{const lines=cart.map(i=>({merchandiseId:i.variantId,quantity:i.quantity}));if(lines.some(x=>!x.merchandiseId))throw Error("A product is missing a Shopify variant.");const d=await api("mutation AurenCreateCart($input: CartInput!) { cartCreate(input: $input) { cart { checkoutUrl } userErrors { field message } } }",{input:{lines:lines}});const r=d.cartCreate;if(r.userErrors.length)throw Error(r.userErrors.map(x=>x.message).join(", "));if(!r.cart||!r.cart.checkoutUrl)throw Error("Shopify did not return a checkout URL.");location.href=r.cart.checkoutUrl}catch(e){console.error(e);toast(e.message||"Could not start checkout.")}}
$("checkoutButton").addEventListener("click",checkout);renderProducts();renderCart();loadShopify();
})();